### ISSUE TITLE
New structure for 0.88 and up

### ISSUE THREAD

**Issue by godinperson** [ksheumaker/homeassistant-aerogarden#3]
Hi,

I want to use your aerogarden. However, I'm on 0.88b4 and it needs a new structure. Per https://rc--home-assistant-docs.netlify.com/blog/2019/02/13/release-88/

Note for custom component developers: We are moving to a new file structure. Platforms now live embedded in components. Custom platforms will have to be updated to follow this pattern. This is a breaking change in case your custom platform overrides a built-in platform. Rename your custom platform from, ie light/hue.py to hue/light.py.

I could modify some files but what do I do with the main file?

Thanks

**Comment by ksheumaker** [comment]
Thanks for the heads up.  I haven't looked into the 0.88 release, let me go through the docs, and see what I can do to fix it.

**Comment by ksheumaker** [comment]
Should be fixed with the latest code update.

**Comment by godinperson** [comment]
I'm getting a Component not found: aerogarden in my config.

Thanks

**Comment by ksheumaker** [comment]
You have the directory structure like this?

```
   config/custom_components/aerogarden/__init__.py
   config/custom_components/aerogarden/binary_sensor.py
   config/custom_components/aerogarden/sensor.py
   config/custom_components/aerogarden/light.py
```

It's working in my 0.88.1 setup.  Did you remove the old install from the custom_components?

**Comment by godinperson** [comment]
It does work. Didn't think __init__.py was needed. Thanks for the plugin!

**Comment by ksheumaker** [comment]
No problem, with this new structure __init__.py is the old aerogarden.py that was in custom_components/
